"""
Agent 4: Churn Prevention
Schedule: Daily at 10am IST
Input: Customers with >3 orders in last 60 days AND no order in last 14 days (churned high-value)
Output: DRAFT campaign targeting these customers with personalised message + discount offer
"""
import httpx
import logging
from datetime import datetime, timedelta
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

CHURN_WINDOW_DAYS = 14
QUALIFYING_ORDER_COUNT = 3
QUALIFYING_PERIOD_DAYS = 60
RECOVERY_DISCOUNT_PERCENT = 15


async def run_churn_prevention() -> Dict[str, Any]:
    from ..utils.config import get_config
    config = get_config()
    backend_url = config.backend_url

    if not config.agent_token:
        logger.warning("AGENT_TOKEN not set — churn prevention skipped")
        return {"error": "AGENT_TOKEN not configured"}

    headers = {"Authorization": f"Bearer {config.agent_token}", "Content-Type": "application/json"}

    campaigns_created = 0
    customers_targeted = 0

    async with httpx.AsyncClient(timeout=30.0) as client:
        stores = await _get_stores(client, backend_url, headers)

        for store in stores:
            store_id = store["id"]
            churned_customers = await _find_churned_customers(client, backend_url, headers, store_id)

            if not churned_customers:
                continue

            customers_targeted += len(churned_customers)

            top_items = await _get_top_items(client, backend_url, headers, store_id)
            top_item_names = [item.get("name", "our bestsellers") for item in top_items[:3]]

            campaign_payload = {
                "storeId": store_id,
                "name": f"Win-Back Campaign — {datetime.now().strftime('%Y-%m-%d')}",
                "type": "WIN_BACK",
                "status": "DRAFT",
                "autoGenerated": True,
                "targetSegment": "CHURNED_HIGH_VALUE",
                "customerIds": [c["id"] for c in churned_customers],
                "discountPercent": RECOVERY_DISCOUNT_PERCENT,
                "message": (
                    f"We miss you! Come back and enjoy {RECOVERY_DISCOUNT_PERCENT}% off your next order. "
                    f"Our {', '.join(top_item_names)} are waiting for you."
                ),
                "expiresInDays": 7,
                "generatedBy": "churn_prevention_agent",
                "generatedAt": datetime.now().isoformat(),
            }

            res = await client.post(
                f"{backend_url}/api/campaigns",
                json=campaign_payload,
                headers=headers,
            )

            if res.status_code in (200, 201):
                campaigns_created += 1
                await _notify_managers(
                    client, backend_url, headers, store_id,
                    f"Churn Alert: {len(churned_customers)} high-value customers haven't ordered in "
                    f"{CHURN_WINDOW_DAYS}+ days. A win-back campaign draft is ready for your review.",
                )

    logger.info("Churn prevention complete: %d campaigns, %d customers", campaigns_created, customers_targeted)
    return {"campaigns_created": campaigns_created, "customers_targeted": customers_targeted}


async def _find_churned_customers(
    client: httpx.AsyncClient, backend_url: str, headers: dict, store_id: str,
) -> List[Dict]:
    """Find customers who ordered >3 times in last 60 days but not in last 14 days."""
    res = await client.get(
        f"{backend_url}/api/customers",
        params={"storeId": store_id, "filter": "CHURNED_HIGH_VALUE"},
        headers=headers,
    )
    if res.status_code == 200:
        data = res.json()
        return data if isinstance(data, list) else data.get('content') or []

    # Fallback: get all customers and filter in Python
    all_res = await client.get(
        f"{backend_url}/api/customers",
        params={"storeId": store_id},
        headers=headers,
    )
    if all_res.status_code != 200:
        return []

    all_customers = all_res.json().get("content") or all_res.json()
    churn_cutoff = datetime.now() - timedelta(days=CHURN_WINDOW_DAYS)

    churned = []
    for customer in all_customers:
        last_order = customer.get("lastOrderDate")
        total_orders = customer.get("totalOrders", 0)
        if last_order and total_orders >= QUALIFYING_ORDER_COUNT:
            last_order_dt = datetime.fromisoformat(last_order.replace("Z", "+00:00"))
            if last_order_dt < churn_cutoff:
                churned.append(customer)

    return churned


async def _get_top_items(
    client: httpx.AsyncClient, backend_url: str, headers: dict, store_id: str,
) -> List[Dict]:
    res = await client.get(
        f"{backend_url}/api/analytics/products",
        params={"storeId": store_id},
        headers=headers,
    )
    if res.status_code == 200:
        data = res.json()
        if isinstance(data, list):
            return data[:3]
        items = data.get("topItems") or data.get("items") or []
        return items[:3]
    return []


async def _get_stores(client: httpx.AsyncClient, backend_url: str, headers: dict) -> List[Dict]:
    res = await client.get(f"{backend_url}/api/stores", headers=headers)
    if res.status_code != 200:
        return []
    data = res.json()
    return data if isinstance(data, list) else data.get("content") or []


async def _notify_managers(
    client: httpx.AsyncClient, backend_url: str, headers: dict, store_id: str, message: str
):
    managers_res = await client.get(
        f"{backend_url}/api/users",
        params={"type": "MANAGER", "storeId": store_id},
        headers=headers,
    )
    if managers_res.status_code != 200:
        return
    from . import _unwrap
    for manager in _unwrap(managers_res.json()):
        await client.post(
            f"{backend_url}/api/notifications",
            json={
                "userId": manager["id"],
                "type": "CHURN_ALERT",
                "title": "Customer Churn Alert",
                "message": message,
                "priority": "MEDIUM",
            },
            headers=headers,
        )
