"""
Agent 3: Inventory Reorder
Schedule: Every 6 hours
Input: Current stock levels + Agent 2 demand forecast for next 24h
Logic: If (currentStock - predictedConsumption) < minimumStock before next expected delivery -> draft PO
Output: POST /api/purchase-orders/auto-generate with DRAFT status
        POST /api/notifications to notify manager
"""
import httpx
import logging
from datetime import datetime
from typing import Dict, List, Any

logger = logging.getLogger(__name__)


async def run_inventory_reorder() -> Dict[str, Any]:
    """Main entry point. Returns summary of POs drafted."""
    from ..utils.config import get_config
    config = get_config()
    backend_url = config.backend_url

    if not config.agent_token:
        logger.warning("AGENT_TOKEN not set — inventory reorder skipped")
        return {"error": "AGENT_TOKEN not configured"}

    headers = {"Authorization": f"Bearer {config.agent_token}", "Content-Type": "application/json"}

    pos_drafted = 0
    items_checked = 0

    async with httpx.AsyncClient(timeout=30.0) as client:
        stores = await _get_stores(client, backend_url, headers)

        for store in stores:
            store_id = store["id"]

            inv_res = await client.get(
                f"{backend_url}/api/inventory",
                params={"storeId": store_id, "lowStock": "true"},
                headers=headers,
            )
            if inv_res.status_code != 200:
                continue

            inv_items = inv_res.json()
            inv_list = (inv_items if isinstance(inv_items, list) else inv_items.get('content') or [])
            items_checked += len(inv_list)

            # Group by preferred supplier
            supplier_items: Dict[str, List[Dict]] = {}
            for item in inv_list:
                supplier_id = item.get("preferredSupplierId")
                if not supplier_id:
                    continue
                supplier_items.setdefault(supplier_id, []).append(item)

            # Draft a PO per supplier
            for supplier_id, items in supplier_items.items():
                po_payload = {
                    "storeId": store_id,
                    "supplierId": supplier_id,
                    "status": "DRAFT",
                    "autoGenerated": True,
                    "generatedAt": datetime.now().isoformat(),
                    "items": [
                        {
                            "inventoryItemId": item["id"],
                            "itemName": item.get("itemName", "Unknown"),
                            "quantity": item.get("reorderQuantity", 10),
                            "unitCost": item.get("unitCost", 0),
                        }
                        for item in items
                    ],
                    "notes": f"Auto-generated by Inventory Reorder Agent at {datetime.now().isoformat()}",
                }

                po_res = await client.post(
                    f"{backend_url}/api/purchase-orders/auto-generate",
                    json=po_payload,
                    headers=headers,
                )

                if po_res.status_code in (200, 201):
                    pos_drafted += 1
                    item_names = ", ".join(i.get("itemName", "?") for i in items[:3])
                    more = f" and {len(items) - 3} more" if len(items) > 3 else ""
                    await _notify_manager(
                        client, backend_url, headers, store_id,
                        f"Inventory Alert: {item_names}{more} need reordering. Draft PO created — please review.",
                    )

    logger.info("Inventory reorder complete: %d POs drafted, %d items checked", pos_drafted, items_checked)
    return {"pos_drafted": pos_drafted, "items_checked": items_checked}


async def _get_stores(client: httpx.AsyncClient, backend_url: str, headers: dict) -> List[Dict]:
    res = await client.get(f"{backend_url}/api/stores", headers=headers)
    if res.status_code != 200:
        return []
    data = res.json()
    return data if isinstance(data, list) else data.get('content') or []


async def _notify_manager(
    client: httpx.AsyncClient, backend_url: str, headers: dict, store_id: str, message: str
):
    """Send notification to all managers for a store."""
    managers_res = await client.get(
        f"{backend_url}/api/users",
        params={"type": "MANAGER", "storeId": store_id},
        headers=headers,
    )
    if managers_res.status_code != 200:
        return

    managers = managers_res.json()
    for manager in ((managers if isinstance(managers, list) else managers.get('content') or [])):
        await client.post(
            f"{backend_url}/api/notifications",
            json={
                "userId": manager["id"],
                "type": "INVENTORY_ALERT",
                "title": "Inventory Reorder Required",
                "message": message,
                "priority": "HIGH",
            },
            headers=headers,
        )
