"""
Agent 3: Inventory Reorder
Schedule: Every 6 hours
Input: Current stock levels + demand forecast for next 24h
Logic: If low stock → draft PO (PROPOSE) + notify manager
Output: POST /api/purchase-orders/auto-generate with DRAFT status
        POST /api/notifications to notify manager

LLM path: multi-step tool loop (list_low_stock → forecast → create_draft_po → notify).
Fallback: threshold-based draft PO rule path.
"""
import httpx
import logging
from datetime import datetime
from typing import Dict, List, Any

logger = logging.getLogger(__name__)

INVENTORY_INSTRUCTION = """You are MaSoVa Inventory Reorder Agent (ops).

Goal: Keep stores stocked without over-ordering. You PROPOSE draft purchase orders only.

Workflow:
1. Call list_low_stock (optionally scoped by store).
2. Optionally call get_forecast_snippet for high-risk SKUs — use tool numbers only.
3. Group items by preferred_supplier_id and call create_draft_po with justified quantities
   from reorder_quantity / forecast data (never invent stock counts).
4. Call notify_managers with a clear summary and rationale.

Do not claim orders are finalized. Manager approval is required.
"""


def _inventory_llm_runner():
    from ..runtime.ops_llm import make_ops_llm_runner
    from ..runtime.wrap import AGENT_ALLOWLISTS

    return make_ops_llm_runner(
        instruction=INVENTORY_INSTRUCTION,
        tool_names=list(AGENT_ALLOWLISTS["inventory_reorder"]),
    )


async def run_inventory_reorder():
    """Public entry — routes through AgentRuntime with LLM tool loop + rule fallback."""
    from ..runtime.wrap import run_ops_agent
    from ..runtime.ops_llm import ops_prefer_llm

    return await run_ops_agent(
        "inventory_reorder",
        "scheduled",
        _rule_run_inventory_reorder,
        goal="Identify low stock and draft purchase orders for manager approval",
        llm_runner=_inventory_llm_runner() if ops_prefer_llm() else None,
        prefer_llm=ops_prefer_llm(),
    )


async def _rule_run_inventory_reorder() -> Dict[str, Any]:
    """Rule fallback. Returns summary of POs drafted."""
    from ..utils.config import get_config
    config = get_config()
    backend_url = config.backend_url

    if not config.agent_token:
        logger.warning("AGENT_TOKEN not set — inventory reorder skipped")
        return {"error": "AGENT_TOKEN not configured"}

    headers = {"Authorization": f"Bearer {config.agent_token}", "Content-Type": "application/json"}

    pos_drafted = 0
    items_checked = 0

    async with httpx.AsyncClient(timeout=30.0) as client:
        stores = await _get_stores(client, backend_url, headers)

        for store in stores:
            store_id = store["id"]

            inv_res = await client.get(
                f"{backend_url}/api/inventory",
                params={"storeId": store_id, "lowStock": "true"},
                headers=headers,
            )
            if inv_res.status_code != 200:
                continue

            inv_items = inv_res.json()
            inv_list = (inv_items if isinstance(inv_items, list) else inv_items.get('content') or [])
            items_checked += len(inv_list)

            # Group by preferred supplier
            supplier_items: Dict[str, List[Dict]] = {}
            for item in inv_list:
                supplier_id = item.get("preferredSupplierId")
                if not supplier_id:
                    continue
                supplier_items.setdefault(supplier_id, []).append(item)

            # Draft a PO per supplier
            for supplier_id, items in supplier_items.items():
                po_payload = {
                    "storeId": store_id,
                    "supplierId": supplier_id,
                    "status": "DRAFT",
                    "autoGenerated": True,
                    "generatedAt": datetime.now().isoformat(),
                    "items": [
                        {
                            "inventoryItemId": item["id"],
                            "itemName": item.get("itemName", "Unknown"),
                            "quantity": item.get("reorderQuantity", 10),
                            "unitCost": item.get("unitCost", 0),
                        }
                        for item in items
                    ],
                    "notes": f"Auto-generated by Inventory Reorder Agent at {datetime.now().isoformat()}",
                }

                po_res = await client.post(
                    f"{backend_url}/api/purchase-orders/auto-generate",
                    json=po_payload,
                    headers=headers,
                )

                if po_res.status_code in (200, 201):
                    pos_drafted += 1
                    item_names = ", ".join(i.get("itemName", "?") for i in items[:3])
                    more = f" and {len(items) - 3} more" if len(items) > 3 else ""
                    await _notify_manager(
                        client, backend_url, headers, store_id,
                        f"Inventory Alert: {item_names}{more} need reordering. Draft PO created — please review.",
                    )

    logger.info("Inventory reorder complete: %d POs drafted, %d items checked", pos_drafted, items_checked)
    return {
        "pos_drafted": pos_drafted,
        "items_checked": items_checked,
        "summary": f"Rule fallback: {pos_drafted} draft PO(s), {items_checked} items checked",
        "status": "ok",
    }


async def _get_stores(client: httpx.AsyncClient, backend_url: str, headers: dict) -> List[Dict]:
    res = await client.get(f"{backend_url}/api/stores", headers=headers)
    if res.status_code != 200:
        return []
    data = res.json()
    return data if isinstance(data, list) else data.get('content') or []


async def _notify_manager(
    client: httpx.AsyncClient, backend_url: str, headers: dict, store_id: str, message: str
):
    """Send notification to all managers for a store."""
    managers_res = await client.get(
        f"{backend_url}/api/users",
        params={"type": "MANAGER", "storeId": store_id},
        headers=headers,
    )
    if managers_res.status_code != 200:
        return

    managers = managers_res.json()
    for manager in ((managers if isinstance(managers, list) else managers.get('content') or [])):
        await client.post(
            f"{backend_url}/api/notifications",
            json={
                "userId": manager["id"],
                "type": "INVENTORY_ALERT",
                "title": "Inventory Reorder Required",
                "message": message,
                "priority": "HIGH",
            },
            headers=headers,
        )
